import * as THREE from 'three';
import {EffectComposer} from 'three/addons/postprocessing/EffectComposer.js';
import {RenderPass} from 'three/addons/postprocessing/RenderPass.js';
import {UnrealBloomPass} from 'three/addons/postprocessing/UnrealBloomPass.js';
import {ShaderPass} from 'three/addons/postprocessing/ShaderPass.js';
import {OutputPass} from 'three/addons/postprocessing/OutputPass.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
import {TASTE_TEXTURES,personalityColor,makeTexturedMarble,makePlainMarble,setRootColor,disposeRoot} from './emaeaVisualRecipes.js';
import {relationGlobalSpeed,relationIndividualMultipliers} from './emaeaDomainDynamics.js';

const BASE_COUNT=200,SATELLITE_COUNT=5;
const BASE={ECART:28,TAILLE_BILLES:.90,V1:.75,LIBERTE:.15,CHEVAUCHEMENT:1.45,ROTATION:.11,FREQUENCE_INVERSIONS:12,BRILLANCE:.62,INTENSITE_LUMIERE:2.25,LUMIERE_AMBIANTE:1,CAMERA:280};
const goldenAngle=Math.PI*(3-Math.sqrt(5));
const rnd=(a,b)=>THREE.MathUtils.lerp(a,b,Math.random());
const randomDirection=()=>new THREE.Vector3(Math.random()*2-1,Math.random()*2-1,Math.random()*2-1).normalize();
const clamp01=x=>Math.max(0,Math.min(1,Number(x)||0));
function hash01(text){let h=2166136261;for(const ch of String(text)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return (h>>>0)/4294967296}
function stableOrder(items,salt){return [...items].sort((a,b)=>hash01(`${salt}|${a?.id}`)-hash01(`${salt}|${b?.id}`))}
function fibonacciShell(count,radius,phase,rotation){const pts=[],q=new THREE.Quaternion().setFromEuler(new THREE.Euler(rotation.x,rotation.y,rotation.z));if(count<=0)return pts;for(let i=0;i<count;i++){const y=1-(i+.5)*(2/count),rr=Math.sqrt(Math.max(0,1-y*y)),theta=i*goldenAngle+phase,p=new THREE.Vector3(Math.cos(theta)*rr,y,Math.sin(theta)*rr).multiplyScalar(radius);p.applyQuaternion(q);pts.push(p)}return pts}

/** 200 = référence exacte. Au-delà, les proportions viennent du prototype multi-population existant. */
export function makeEmaeaBodyCenters(count){
  const n=Math.max(1,Number(count)|0),p=[new THREE.Vector3()];
  let counts;
  if(n===200)counts=[12,32,56,99];
  else{const rest=n-1;counts=[.06,.16,.28].map(x=>Math.floor(rest*x));counts.push(rest-counts[0]-counts[1]-counts[2])}
  p.push(...fibonacciShell(counts[0],.95,.18,new THREE.Vector3(.22,-.14,.31)),...fibonacciShell(counts[1],1.58,1.07,new THREE.Vector3(-.31,.27,.11)),...fibonacciShell(counts[2],2.18,2.16,new THREE.Vector3(.17,.39,-.26)),...fibonacciShell(counts[3],2.82,2.91,new THREE.Vector3(-.21,-.28,.37)));
  return p;
}
function domainMean(bucket){const xs=Object.values(bucket||{}).filter(v=>v!=null&&Number.isFinite(Number(v))).map(Number);return xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0}
function slot(marble,domain){return marble?.domains?.[domain]??null}
function value(marble,domain){const n=Number(slot(marble,domain)?.value);return Number.isFinite(n)?Math.max(0,Math.min(100,n)):0}
function makeFlashTexture(){const c=document.createElement('canvas');c.width=c.height=128;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(64,64,0,64,64,64);g.addColorStop(0,'rgba(255,255,255,1)');g.addColorStop(.12,'rgba(255,255,255,1)');g.addColorStop(.28,'rgba(255,255,255,.72)');g.addColorStop(.5,'rgba(255,255,255,.24)');g.addColorStop(.72,'rgba(255,255,255,.055)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,128,128);const t=new THREE.CanvasTexture(c);t.minFilter=t.magFilter=THREE.LinearFilter;t.generateMipmaps=false;return t}
function makeHaloTexture(){const c=document.createElement('canvas');c.width=c.height=256;const ctx=c.getContext('2d'),g=ctx.createRadialGradient(128,128,0,128,128,128);g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(.60,'rgba(255,255,255,0)');g.addColorStop(.66,'rgba(255,255,255,.30)');g.addColorStop(.76,'rgba(255,255,255,.16)');g.addColorStop(.88,'rgba(255,255,255,.06)');g.addColorStop(1,'rgba(255,255,255,0)');ctx.fillStyle=g;ctx.fillRect(0,0,256,256);const t=new THREE.CanvasTexture(c);t.minFilter=t.magFilter=THREE.LinearFilter;t.generateMipmaps=false;return t}
function chosenTasteIds(state,activeData){const chosen=new Set(),levels=state?.durable_levels?.['Goûts']||{};for(const [sub,kind] of Object.entries(TASTE_TEXTURES)){const group=activeData.filter(m=>slot(m,'Goûts')?.subdomain===sub),n=Math.floor(group.length*clamp01(Number(levels[sub])/100));for(const m of stableOrder(group,`taste|${sub}`).slice(0,n))chosen.add(`${m.id}|${kind}`)}return chosen}

export function createEmaeaBodyRuntime(container,state){
  if(!container)throw new Error('Conteneur graphique EMÆÄ manquant');
  const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;container.appendChild(renderer.domElement);
  const scene=new THREE.Scene();scene.background=new THREE.Color(0x1d1f22);
  const camera=new THREE.PerspectiveCamera(55,1,.1,3000);camera.position.z=BASE.CAMERA;
  const entityGroup=new THREE.Group();scene.add(entityGroup);
  const satelliteGroup=new THREE.Group();scene.add(satelliteGroup);
  const bloomLayer=1,bloomComposer=new EffectComposer(renderer);bloomComposer.renderToScreen=false;bloomComposer.addPass(new RenderPass(scene,camera));bloomComposer.addPass(new UnrealBloomPass(new THREE.Vector2(1,1),1.15,.28,0));
  const finalComposer=new EffectComposer(renderer);finalComposer.addPass(new RenderPass(scene,camera));const mixPass=new ShaderPass(new THREE.ShaderMaterial({uniforms:{baseTexture:{value:null},bloomTexture:{value:bloomComposer.renderTarget2.texture}},vertexShader:'varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}',fragmentShader:'uniform sampler2D baseTexture;uniform sampler2D bloomTexture;varying vec2 vUv;void main(){gl_FragColor=texture2D(baseTexture,vUv)+texture2D(bloomTexture,vUv);}'}),'baseTexture');mixPass.needsSwap=true;finalComposer.addPass(mixPass);finalComposer.addPass(new OutputPass());
  const pmrem=new THREE.PMREMGenerator(renderer),goldEnv=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();
  const ambient=new THREE.HemisphereLight(0xffffff,0x30343b,BASE.LUMIERE_AMBIANTE);scene.add(ambient);const spot=new THREE.SpotLight(0xffffff,BASE.INTENSITE_LUMIERE,0,Math.PI/3.2,.55,0);spot.position.set(42,28,350);spot.castShadow=true;spot.shadow.mapSize.set(1024,1024);spot.shadow.camera.near=1;spot.shadow.camera.far=700;spot.shadow.bias=-.00035;spot.shadow.normalBias=.015;scene.add(spot);
  const flashTexture=makeFlashTexture(),haloTexture=makeHaloTexture();
  const cellGroup=new THREE.Group();cellGroup.visible=false;entityGroup.add(cellGroup);const cellGeometry=new THREE.SphereGeometry(1,16,12),cellMaterial=new THREE.MeshBasicMaterial({color:0x7f8792,wireframe:true,transparent:true,opacity:.16,depthWrite:false});

  let sourceState=structuredClone(state||{}),disposed=false,raf=0,ecart=BASE.ECART*Math.cbrt(Math.max(BASE_COUNT,sourceState?.marbles?.length||BASE_COUNT)/BASE_COUNT),elapsed=0,sense=1,nextCapacityMove=7;
  const pendingIds=new Set((sourceState?.pending_births||[]).map(x=>String(x?.marble_id??x?.birth_id??'')));
  const activeData=(sourceState?.marbles||[]).filter(m=>!pendingIds.has(String(m?.id)));
  const centers=makeEmaeaBodyCenters(activeData.length),marbles=[],dataById=new Map(activeData.map(m=>[String(m.id),m])),homeSlots=[],directions=[],travel=[],wanderTargets=[],wanderClocks=[],ownWorld=[],cells=[],flashes=[],historyHalos=new Map(),migrationByBead=new Map();
  let tasteChosen=chosenTasteIds(sourceState,activeData),relationMultipliers=relationIndividualMultipliers(activeData);

  function tasteKind(m,chosen=tasteChosen){const sub=slot(m,'Goûts')?.subdomain,kind=TASTE_TEXTURES[sub];return kind&&chosen.has(`${m.id}|${kind}`)?kind:null}
  function addFlash(root,m){const level=value(m,'Opinions/Valeurs')/100;if(!slot(m,'Opinions/Valeurs'))return;const kind=tasteKind(m),mat=new THREE.SpriteMaterial({map:flashTexture,color:0xffffff,transparent:true,opacity:0,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,toneMapped:false}),sp=new THREE.Sprite(mat);sp.layers.set(bloomLayer);sp.visible=false;root.add(sp);flashes.push({sp,root,id:String(m.id),level,radius:kind?1.10:6.18,baseSize:kind?.07:.42,normal:new THREE.Vector3(),wait:Math.random()*(2.6-2.1*level),age:99,duration:.045})}
  function createVisual(m){const kind=tasteKind(m),visual=kind?makeTexturedMarble(kind,m,BASE.BRILLANCE):makePlainMarble(m,BASE.BRILLANCE),root=new THREE.Group();root.userData.emaeaId=String(m.id);root.userData.textureUnitScale=kind?6:1;root.userData.tasteKind=kind;visual.userData.primaryMarbleMesh=true;root.add(visual);root.scale.setScalar(BASE.TAILLE_BILLES*root.userData.textureUnitScale);root.traverse(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true}});addFlash(root,m);return root}
  function appendMotion(root,m,index){marbles.push(root);homeSlots.push(index);directions.push(randomDirection());travel.push(new THREE.Vector3());wanderTargets.push(randomDirection());wanderClocks.push(Math.random()*2.5);ownWorld.push({axis:randomDirection(),variation:rnd(.85,1.15)});const c=new THREE.Mesh(cellGeometry,cellMaterial);cellGroup.add(c);cells.push(c);dataById.set(String(m.id),m)}
  activeData.forEach((m,i)=>{const root=createVisual(m);entityGroup.add(root);appendMotion(root,m,i)});

  const satelliteData=[{radius:103,speed:.19,phase:.40,tiltX:.55,tiltZ:.18},{radius:112,speed:-.14,phase:1.70,tiltX:-.38,tiltZ:.72},{radius:98,speed:.23,phase:2.95,tiltX:.22,tiltZ:-.61},{radius:108,speed:-.17,phase:4.15,tiltX:.68,tiltZ:-.27},{radius:101,speed:.15,phase:5.45,tiltX:-.52,tiltZ:-.76}],satellites=[];
  for(let i=0;i<SATELLITE_COUNT;i++){const m=activeData[i]??{domains:{'Personnalité':{subdomain:'Curiosité',value:0}}},s=makePlainMarble(m,BASE.BRILLANCE);s.scale.setScalar(BASE.TAILLE_BILLES);s.castShadow=s.receiveShadow=true;satelliteGroup.add(s);satellites.push(s)}

  function updateCells(){const r=ecart*BASE.LIBERTE*BASE.CHEVAUCHEMENT;for(let i=0;i<cells.length;i++){const p=centers[homeSlots[i]];if(!p)continue;cells[i].position.copy(p).multiplyScalar(ecart);cells[i].scale.setScalar(r)}}
  function applyHistoryHalos(){const level=Math.max(0,Math.min(100,Number(sourceState?.history_level??0))),wanted=new Set(stableOrder([...dataById.values()],`history`).slice(0,Math.round(marbles.length*level/100)).map(m=>String(m.id)));for(let i=0;i<marbles.length;i++){const root=marbles[i],id=String(root.userData.emaeaId);if(wanted.has(id)&&!historyHalos.has(id)){const sp=new THREE.Sprite(new THREE.SpriteMaterial({map:haloTexture,color:personalityColor(dataById.get(id)),transparent:true,opacity:.72,depthWrite:false,depthTest:true,blending:THREE.AdditiveBlending,toneMapped:false}));sp.scale.setScalar(19.2/(root.userData.textureUnitScale||1));sp.renderOrder=0;root.add(sp);historyHalos.set(id,sp)}else if(!wanted.has(id)&&historyHalos.has(id)){const sp=historyHalos.get(id);root.remove(sp);sp.material.dispose();historyHalos.delete(id)}else if(wanted.has(id)&&historyHalos.has(id)){const sp=historyHalos.get(id);sp.scale.setScalar(19.2/(root.userData.textureUnitScale||1));if(sp.material?.color)sp.material.color.copy(personalityColor(dataById.get(id)))}}}
  function replaceTasteVisual(root,m,nextKind){
    const previous=root.children.find(x=>x?.userData?.primaryMarbleMesh===true);
    if(previous){root.remove(previous);disposeRoot(previous)}
    const visual=nextKind?makeTexturedMarble(nextKind,m,BASE.BRILLANCE):makePlainMarble(m,BASE.BRILLANCE);
    visual.userData.primaryMarbleMesh=true;visual.traverse?.(x=>{if(x.isMesh){x.castShadow=true;x.receiveShadow=true}});root.add(visual);
    root.userData.tasteKind=nextKind;root.userData.textureUnitScale=nextKind?6:1;root.scale.setScalar(BASE.TAILLE_BILLES*root.userData.textureUnitScale);
    const f=flashes.find(x=>x.root===root);if(f){f.radius=nextKind?1.10:6.18;f.baseSize=nextKind?.07:.42;if(f.normal.lengthSq()>0)f.sp.position.copy(f.normal).multiplyScalar(f.radius)}
    const halo=historyHalos.get(String(root.userData.emaeaId));if(halo)halo.scale.setScalar(19.2/(root.userData.textureUnitScale||1));
  }
  function refreshTasteVisuals(next){
    const active=marbles.map(root=>dataById.get(String(root.userData.emaeaId))).filter(Boolean),nextChosen=chosenTasteIds(next,active);tasteChosen=nextChosen;
    for(const root of marbles){const id=String(root.userData.emaeaId),m=dataById.get(id);if(!m)continue;const nextKind=tasteKind(m,nextChosen),previousKind=root.userData.tasteKind??null;if(nextKind!==previousKind)replaceTasteVisual(root,m,nextKind);setRootColor(root,personalityColor(m))}
  }
  applyHistoryHalos();updateCells();

  const capacityMask=()=>{const level=Math.max(0,Math.min(100,Number(sourceState?.durable_levels?.Capacités??0))),ids=stableOrder([...dataById.values()],`capacity`).slice(0,Math.round(marbles.length*level/100));return new Set(ids.map(x=>String(x.id)))};
  function capacityDelay(){const level=Math.max(0,Math.min(100,Number(sourceState?.durable_levels?.Capacités??0))),t=THREE.MathUtils.clamp((level-30)/60,0,1);return rnd(THREE.MathUtils.lerp(4.5,2,t),THREE.MathUtils.lerp(10,4.75,t))}
  function startCapacitySwap(){const capable=capacityMask(),eligible=[];for(let i=0;i<marbles.length;i++)if(capable.has(String(marbles[i].userData.emaeaId))&&!migrationByBead.has(i))eligible.push(i);if(eligible.length<2)return;const a=eligible[Math.floor(Math.random()*eligible.length)];let b=a;while(b===a)b=eligible[Math.floor(Math.random()*eligible.length)];const slotA=homeSlots[a],slotB=homeSlots[b],fromA=centers[slotA].clone().multiplyScalar(ecart),fromB=centers[slotB].clone().multiplyScalar(ecart),toA=centers[slotB].clone().multiplyScalar(ecart),toB=centers[slotA].clone().multiplyScalar(ecart);travel[a].set(0,0,0);travel[b].set(0,0,0);migrationByBead.set(a,{from:fromA,to:toA,age:0,duration:1.7+Math.random()*.8,targetSlot:slotB,delay:0});migrationByBead.set(b,{from:fromB,to:toB,age:0,duration:1.7+Math.random()*1.6,targetSlot:slotA,delay:.9+Math.random()*1.6})}
  function updateMigration(i,dt){const m=migrationByBead.get(i);if(!m)return false;if(m.delay>0){m.delay-=dt;return true}m.age+=dt;const t=Math.min(1,m.age/m.duration),s=t*t*(3-2*t),arc=Math.sin(Math.PI*t)*ecart*.12,mid=m.from.clone().lerp(m.to,s),side=new THREE.Vector3().crossVectors(m.from,m.to);if(side.lengthSq()<1e-6)side.set(0,1,0);side.normalize().multiplyScalar(arc);marbles[i].position.copy(mid.add(side));if(t>=1){homeSlots[i]=m.targetSlot;travel[i].set(0,0,0);directions[i].copy(randomDirection());wanderTargets[i].copy(randomDirection());wanderClocks[i]=.8+Math.random()*2.4;migrationByBead.delete(i)}return true}

  const KNOWLEDGE_ON=2.5,OFF_MIN=5,OFF_MAX=9,AFTER_LIFE=3,AFTER_SPACING=.42,AFTER_SIZE=9.4,AFTER_ALPHA=.27,PER_BEAD=220;
  let afterMesh=null,afterGeometry=null,afterPositions=null,afterColors=null,afterSizes=null,afterAlphas=null,afterAges=null,afterLives=null,afterAlive=null,afterHeads=null,knowledgeStates=[],prevWorld=[];
  function rebuildAfterimages(){if(afterMesh){scene.remove(afterMesh);afterGeometry.dispose();afterMesh.material.dispose()}const cap=Math.max(1,marbles.length*PER_BEAD);afterPositions=new Float32Array(cap*3);afterColors=new Float32Array(cap*3);afterSizes=new Float32Array(cap);afterAlphas=new Float32Array(cap);afterAges=new Float32Array(cap);afterLives=new Float32Array(cap);afterAlive=new Uint8Array(cap);afterHeads=new Uint16Array(marbles.length);const base=new THREE.PlaneGeometry(1,1);afterGeometry=new THREE.InstancedBufferGeometry();afterGeometry.index=base.index;afterGeometry.setAttribute('position',base.attributes.position);afterGeometry.setAttribute('uv',base.attributes.uv);afterGeometry.setAttribute('iPos',new THREE.InstancedBufferAttribute(afterPositions,3));afterGeometry.setAttribute('iColor',new THREE.InstancedBufferAttribute(afterColors,3));afterGeometry.setAttribute('iSize',new THREE.InstancedBufferAttribute(afterSizes,1));afterGeometry.setAttribute('iAlpha',new THREE.InstancedBufferAttribute(afterAlphas,1));afterGeometry.instanceCount=cap;const material=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,depthFunc:THREE.LessDepth,toneMapped:false,blending:THREE.NormalBlending,vertexShader:'attribute vec3 iPos;attribute vec3 iColor;attribute float iSize;attribute float iAlpha;varying vec2 vUv;varying vec3 vColor;varying float vAlpha;void main(){vUv=uv;vColor=iColor;vAlpha=iAlpha;vec4 center=modelViewMatrix*vec4(iPos,1.0);center.xy+=position.xy*iSize;gl_Position=projectionMatrix*center;}',fragmentShader:'varying vec2 vUv;varying vec3 vColor;varying float vAlpha;void main(){float d=length(vUv-.5);float body=1.0-smoothstep(.05,.46,d);float feather=1.0-smoothstep(.25,.52,d);float a=(body*.66+feather*.34)*vAlpha;if(a<.004)discard;gl_FragColor=vec4(vColor,a);}'});afterMesh=new THREE.Mesh(afterGeometry,material);afterMesh.frustumCulled=false;afterMesh.renderOrder=2;scene.add(afterMesh);knowledgeStates=marbles.map((root,i)=>{const level=value(dataById.get(String(root.userData.emaeaId)),'Connaissances')/100,off=THREE.MathUtils.lerp(OFF_MAX,OFF_MIN,level)*rnd(.72,1.28);return{active:false,phase:Math.random()*off,off,level}});prevWorld=marbles.map(root=>{const p=new THREE.Vector3();root.getWorldPosition(p);return p})}
  rebuildAfterimages();
  function emitAfter(i,p){const cap=afterAlive.length,slotIndex=i*PER_BEAD+(afterHeads[i]||0);if(slotIndex>=cap)return;afterHeads[i]=((afterHeads[i]||0)+1)%PER_BEAD;const o=slotIndex*3,c=personalityColor(dataById.get(String(marbles[i].userData.emaeaId)));afterPositions[o]=p.x;afterPositions[o+1]=p.y;afterPositions[o+2]=p.z;afterColors[o]=c.r;afterColors[o+1]=c.g;afterColors[o+2]=c.b;afterSizes[slotIndex]=AFTER_SIZE;afterAlphas[slotIndex]=AFTER_ALPHA;afterAges[slotIndex]=0;afterLives[slotIndex]=AFTER_LIFE;afterAlive[slotIndex]=1}
  const world=new THREE.Vector3(),emit=new THREE.Vector3();
  function updateKnowledge(dt){for(let s=0;s<afterAlive.length;s++){if(!afterAlive[s])continue;afterAges[s]+=dt;if(afterAges[s]>=afterLives[s]){afterAlive[s]=0;afterAlphas[s]=0;continue}const u=afterAges[s]/afterLives[s];afterAlphas[s]=AFTER_ALPHA*Math.pow(1-u,1.42);afterSizes[s]=AFTER_SIZE*(1-.06*u)}for(let i=0;i<marbles.length;i++){const st=knowledgeStates[i];if(!st)continue;marbles[i].getWorldPosition(world);const prev=prevWorld[i],dist=world.distanceTo(prev);st.level=value(dataById.get(String(marbles[i].userData.emaeaId)),'Connaissances')/100;st.phase+=dt;if(st.active&&st.phase>=KNOWLEDGE_ON){st.active=false;st.phase=0;st.off=THREE.MathUtils.lerp(OFF_MAX,OFF_MIN,st.level)*rnd(.72,1.28)}else if(!st.active&&st.phase>=st.off){st.active=true;st.phase=0}if(st.active&&dist>.001){const n=Math.max(1,Math.ceil(dist/AFTER_SPACING));for(let k=0;k<n;k++){emit.copy(prev).lerp(world,k/n);emitAfter(i,emit)}}prev.copy(world)}for(const key of ['iPos','iColor','iSize','iAlpha'])afterGeometry.attributes[key].needsUpdate=true}

  function updateFlash(dt){const worldN=new THREE.Vector3(),worldP=new THREE.Vector3(),toCamera=new THREE.Vector3(),q=new THREE.Quaternion();for(const f of flashes){const current=dataById.get(f.id);f.level=value(current,'Opinions/Valeurs')/100;if(f.age<f.duration){f.age+=dt;f.root.getWorldQuaternion(q);worldN.copy(f.normal).applyQuaternion(q).normalize();f.sp.getWorldPosition(worldP);toCamera.copy(camera.position).sub(worldP).normalize();const facing=Math.max(0,worldN.dot(toCamera)),t=Math.min(1,f.age/f.duration),pulse=Math.pow(Math.sin(Math.PI*t),.22),visibility=Math.pow(facing,1.8);f.sp.material.opacity=Math.min(1,pulse*visibility*2.8);f.sp.scale.setScalar(f.baseSize*(1.1+6.2*pulse)*(.35+.65*visibility));if(f.age>=f.duration)f.sp.visible=false}else{f.wait-=dt;if(f.wait<=0){f.normal.copy(randomDirection());f.sp.position.copy(f.normal).multiplyScalar(f.radius);f.age=0;f.duration=.035+Math.random()*.045;const activity=.12+.88*f.level*f.level;f.wait=.12+Math.random()*(2.8-2.55*activity);f.sp.visible=true}}}}

  const clock=new THREE.Clock(),axis=randomDirection(),inward=new THREE.Vector3(),steer=new THREE.Vector3();
  function animate(){if(disposed)return;raf=requestAnimationFrame(animate);const dt=Math.min(clock.getDelta(),.04);elapsed+=dt;nextCapacityMove-=dt;if(nextCapacityMove<=0){startCapacitySwap();nextCapacityMove=capacityDelay()}updateFlash(dt);const maxR=ecart*BASE.LIBERTE*BASE.CHEVAUCHEMENT,relationLevel=domainMean(sourceState?.durable_levels?.Relation),gs=relationGlobalSpeed(relationLevel)*ecart*.42;for(let i=0;i<marbles.length;i++){if(updateMigration(i,dt))continue;wanderClocks[i]-=dt;if(wanderClocks[i]<=0){wanderClocks[i]=.8+Math.random()*2.4;wanderTargets[i]=randomDirection()}const d=travel[i].length(),ret=maxR>0?THREE.MathUtils.smoothstep(d/maxR,.55,1):1;inward.copy(travel[i]);if(inward.lengthSq()>0)inward.normalize().multiplyScalar(-1);steer.copy(wanderTargets[i]).multiplyScalar(.3).addScaledVector(inward,ret*1.55);directions[i].addScaledVector(steer,dt).normalize();travel[i].addScaledVector(directions[i],gs*(relationMultipliers[i]??1)*dt);if(maxR<=0)travel[i].set(0,0,0);else if(travel[i].length()>maxR*.985){const normal=travel[i].clone().normalize(),outward=directions[i].dot(normal);if(outward>0)directions[i].addScaledVector(normal,-2*outward).addScaledVector(randomDirection(),.12).normalize();else directions[i].addScaledVector(normal,-.18).normalize();travel[i].setLength(maxR*.955)}const center=centers[homeSlots[i]];if(center)marbles[i].position.copy(center).multiplyScalar(ecart).add(travel[i]);const m=dataById.get(String(marbles[i].userData.emaeaId)),ow=ownWorld[i];marbles[i].rotateOnAxis(ow.axis,6*(value(m,'Monde propre')/100)*ow.variation*dt)}if(Math.random()<1-Math.exp(-(BASE.FREQUENCE_INVERSIONS/60)*dt))sense*=-1;entityGroup.rotateOnWorldAxis(axis,BASE.ROTATION*sense*dt);entityGroup.updateMatrixWorld(true);updateKnowledge(dt);for(let i=0;i<SATELLITE_COUNT;i++){const s=satelliteData[i],a=s.phase+elapsed*s.speed,p=new THREE.Vector3(Math.cos(a)*s.radius,0,Math.sin(a)*s.radius).applyEuler(new THREE.Euler(s.tiltX,0,s.tiltZ));satellites[i].position.copy(p)}const bg=scene.background;scene.background=new THREE.Color(0);camera.layers.set(bloomLayer);bloomComposer.render(dt);scene.background=bg;camera.layers.set(0);camera.layers.enable(bloomLayer);finalComposer.render(dt);camera.layers.set(0)}

  function resize(){const w=Math.max(1,container.clientWidth),h=Math.max(1,container.clientHeight);renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();bloomComposer.setSize(w,h);finalComposer.setSize(w,h)}
  const ro=new ResizeObserver(resize);ro.observe(container);resize();animate();

  function applyState(next){if(!next)return;sourceState=structuredClone(next);const nextById=new Map((next.marbles||[]).map(m=>[String(m.id),m]));for(const root of marbles){const id=String(root.userData.emaeaId),m=nextById.get(id);if(!m)continue;dataById.set(id,m)}refreshTasteVisuals(next);applyHistoryHalos()}
  function createBirthMarble(m){const mesh=makePlainMarble(m,BASE.BRILLANCE);mesh.userData.emaeaId=String(m.id);return mesh}
  function targetForBirth(id,count){const generated=makeEmaeaBodyCenters(count);return generated[count-1].clone()}
  async function normalMaterialForBirth(m){return{color:personalityColor(m),metalness:.02,roughness:1-BASE.BRILLANCE,envMapIntensity:0}}
  async function finalizeBornMarble(mesh,m,command){const index=marbles.length;if(command.body_count_after!==index+1)throw new Error('Ordre de naissance EMÆÄ incohérent');const generated=makeEmaeaBodyCenters(command.body_count_after),target=generated[command.body_count_after-1].clone();centers.push(target);const root=new THREE.Group();root.userData.emaeaId=String(m.id);root.userData.textureUnitScale=1;root.userData.tasteKind=null;entityGroup.remove(mesh);mesh.userData.primaryMarbleMesh=true;root.add(mesh);entityGroup.add(root);mesh.position.set(0,0,0);mesh.scale.setScalar(1);if(mesh.material){mesh.material.color.copy(personalityColor(m));mesh.material.metalness=.02;mesh.material.roughness=1-BASE.BRILLANCE;mesh.material.envMap=null;mesh.material.envMapIntensity=0;mesh.material.needsUpdate=true}appendMotion(root,m,index);relationMultipliers=relationIndividualMultipliers([...dataById.values()]);root.position.copy(target).multiplyScalar(ecart);addFlash(root,m);sourceState={...sourceState,marbles:[...(sourceState.marbles||[]).filter(x=>String(x.id)!==String(m.id)),m]};refreshTasteVisuals(sourceState);applyHistoryHalos();rebuildAfterimages();updateCells()}
  function dispose(){disposed=true;cancelAnimationFrame(raf);ro.disconnect();renderer.domElement.remove();scene.traverse(o=>{o.geometry?.dispose?.();if(Array.isArray(o.material))o.material.forEach(m=>m?.dispose?.());else o.material?.dispose?.()});flashTexture.dispose();haloTexture.dispose();goldEnv.dispose();bloomComposer.dispose?.();finalComposer.dispose?.();renderer.dispose();marbles.forEach(disposeRoot)}

  return{scene,renderer,camera,entityGroup,centers,marbles,updateCells,goldEnv,marbleScale:BASE.TAILLE_BILLES,applyState,createBirthMarble,finalizeBornMarble,targetForBirth,normalMaterialForBirth,getEcart:()=>ecart,setEcart:v=>{ecart=Number(v);updateCells()},dispose};
}
