import React, { useEffect, useRef, useState } from "react";
import { ArrowUp, Paperclip, RotateCcw } from "lucide-react";
import EntityMessage from "@/components/entity/EntityMessage";
const INITIAL_MESSAGE="Bonjour, moi c’est Entity. Et toi ?",ENTITY_ID_KEY="entity-instance-id",ENTITY_MESSAGES_KEY="entity-conversation";
const initialConversation=()=>[{role:"assistant",content:INITIAL_MESSAGE,timestamp:Date.now()}];
function getEntityId(){let id=localStorage.getItem(ENTITY_ID_KEY);if(!id){id=crypto.randomUUID();localStorage.setItem(ENTITY_ID_KEY,id)}return id}
function resetEntityId(){const id=crypto.randomUUID();localStorage.setItem(ENTITY_ID_KEY,id);return id}
function loadConversation(){try{const x=JSON.parse(localStorage.getItem(ENTITY_MESSAGES_KEY)||"null");return Array.isArray(x)&&x.length?x:initialConversation()}catch{return initialConversation()}}
async function invokeEntity(message,entityId,requestId){let last;for(let attempt=0;attempt<2;attempt++){try{const response=await fetch("/api/entity",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message,entityId,requestId})});let data={};try{data=await response.json()}catch{}if(response.ok)return data;last=new Error(data?.error||"Erreur serveur");if(![409,500,502,503,504].includes(response.status)||attempt===1)throw last}catch(error){last=error;if(attempt===1)throw error}await new Promise(r=>setTimeout(r,250))}throw last||new Error("Erreur serveur")}
export default function Entity(){const[entityId,setEntityId]=useState(()=>getEntityId()),[messages,setMessages]=useState(loadConversation),[input,setInput]=useState(""),[loading,setLoading]=useState(false);const scrollRef=useRef(null),inputRef=useRef(null);
useEffect(()=>{localStorage.setItem(ENTITY_MESSAGES_KEY,JSON.stringify(messages.slice(-200)))},[messages]);
useEffect(()=>{scrollRef.current?.scrollTo({top:scrollRef.current.scrollHeight,behavior:"smooth"})},[messages,loading]);
async function handleSend(e){e?.preventDefault();const text=input.trim();if(!text||loading)return;const requestId=crypto.randomUUID();setMessages(p=>[...p,{role:"user",content:text,timestamp:Date.now(),requestId}]);setInput("");setLoading(true);try{const data=await invokeEntity(text,entityId,requestId);setMessages(p=>[...p,{role:"assistant",content:data.message,timestamp:Date.now(),requestId}])}catch(error){setMessages(p=>[...p,{role:"assistant",content:"Je n'ai pas pu répondre cette fois. Réessaie dans un instant.",timestamp:Date.now(),requestId,error:true}]);console.error("Entité:",error)}finally{setLoading(false);inputRef.current?.focus()}}
function handleReset(){setEntityId(resetEntityId());const fresh=initialConversation();localStorage.removeItem(ENTITY_MESSAGES_KEY);setMessages(fresh);setInput("");setTimeout(()=>inputRef.current?.focus(),50)}
return <div className="min-h-screen bg-[#11110f] text-stone-100 flex flex-col"><header className="sticky top-0 z-20 border-b border-white/[0.06] bg-[#11110f]/90 backdrop-blur-xl"><div className="mx-auto flex h-16 w-full max-w-5xl items-center justify-between px-5 sm:px-8"><div className="flex items-center gap-3"><div className="flex h-7 w-7 items-center justify-center rounded-full border border-white/15"><span className="h-1.5 w-1.5 rounded-full bg-stone-200"/></div><div><div className="text-[14px] font-medium tracking-wide text-stone-100">L'Entité</div><div className="text-[10px] tracking-[0.16em] text-stone-600 uppercase">conversation</div></div></div><button type="button" onClick={handleReset} className="inline-flex h-9 items-center gap-2 rounded-full px-3 text-xs text-stone-500 transition-colors hover:bg-white/[0.05] hover:text-stone-300" title="Nouvelle Entity de test"><RotateCcw className="h-3.5 w-3.5"/><span className="hidden sm:inline">Nouveau</span></button></div></header><main ref={scrollRef} className="flex-1 overflow-y-auto"><div className="mx-auto flex min-h-full w-full max-w-3xl flex-col px-5 sm:px-8"><div className="space-y-7 pb-36 pt-10">{messages.map((m,i)=><EntityMessage key={`${m.role}-${i}`} role={m.role} content={m.content}/>)}{loading&&<div className="flex items-center gap-2 px-1 py-3 text-stone-600"><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-stone-500"/><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-stone-600 [animation-delay:150ms]"/><span className="h-1.5 w-1.5 animate-pulse rounded-full bg-stone-700 [animation-delay:300ms]"/></div>}</div></div></main><div className="sticky bottom-0 z-20 bg-gradient-to-t from-[#11110f] via-[#11110f] to-transparent px-4 pb-5 pt-8 sm:px-6 sm:pb-7"><form onSubmit={handleSend} className="mx-auto max-w-3xl"><div className="rounded-[26px] border border-white/[0.1] bg-[#1a1a17] p-2 shadow-2xl shadow-black/20 transition-colors focus-within:border-white/[0.18]"><textarea ref={inputRef} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();handleSend()}}} rows={1} placeholder="Répondre…" disabled={loading} className="max-h-40 min-h-[54px] w-full resize-none bg-transparent px-4 pb-2 pt-3 text-[15px] leading-6 text-stone-100 outline-none placeholder:text-stone-600"/><div className="flex items-center justify-between px-1 pb-1"><button type="button" className="flex h-9 w-9 cursor-not-allowed items-center justify-center rounded-full text-stone-600" title="Ajout de fichiers — prochaine étape" aria-label="Ajouter un fichier" disabled><Paperclip className="h-4 w-4"/></button><button type="submit" disabled={!input.trim()||loading} className="flex h-9 w-9 items-center justify-center rounded-full bg-stone-100 text-[#11110f] transition-all hover:bg-white disabled:scale-95 disabled:bg-stone-700 disabled:text-stone-500" aria-label="Envoyer"><ArrowUp className="h-4 w-4"/></button></div></div></form></div></div>}
